#sub_path_only rewrite ^__PATH__$ __PATH__/ permanent;
location __PATH__/ {

  # Path to source
  root __INSTALL_DIR__/public;

  index index.php;

  # Common parameter to increase upload size limit in conjunction with dedicated PHP-FPM file
  client_max_body_size 50M;

  try_files $uri $uri/ index.php;

  location ~ [^/]\.php(/|$) {
    fastcgi_split_path_info ^(.+?\.php)(/.*)$;
    fastcgi_pass unix:/var/run/php/php__PHP_VERSION__-fpm-__APP__.sock;
    include fastcgi_params_with_auth;
  }

  location ~* ^\/(?!cache).*\.(?:jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc|webp|woff|woff2)$ {
    expires max;
    access_log off;
    more_set_headers "Cache-Control: public";
  }

  location = /favicon.ico { access_log off; log_not_found off; }
  location = /robots.txt  { access_log off; log_not_found off; }

  error_page 404 /index.php;

  location ~ /\.(?!well-known).* {
      deny all;
  }
}
